bag/urls.py
"""
Bag URL Configuration
"""
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

products/urls.py
"""
Products URL Configuration
"""
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/',
         views.delete_product, name='delete_product'),
]

tcc/urls.py
"""tcc URL Configuration"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from .views import handler404, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('company/', include('company.urls')),
    path('favicon.ico',
         RedirectView.as_view(
            url=staticfiles_storage.url('images/favicon.ico')
            ),),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# override the standard error handlers
handler403 = 'tcc.views.handler403'
handler404 = 'tcc.views.handler404'
handler405 = 'tcc.views.handler405'
handler500 = 'tcc.views.handler500'

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings
from django_countries.fields import CountryField
from products.models import Product
from profiles.models import UserProfile


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True,
                                     related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    county = models.CharField(max_length=80, null=True, blank=True)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    order_date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(max_digits=6,
                                        decimal_places=2, null=False,
                                        default=0)
    order_total = models.DecimalField(max_digits=10,
                                      decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(max_digits=10,
                                      decimal_places=2, null=False, default=0)
    original_bag = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(max_length=254, null=False,
                                  blank=False, default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = \
            self.lineitems.aggregate(Sum('lineitem_total'))['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = \
                self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False,
                              on_delete=models.CASCADE,
                              related_name='lineitems')
    product = models.ForeignKey(Product,
                                null=False,
                                blank=False,
                                on_delete=models.CASCADE)
    product_size = models.CharField(max_length=6, null=True, blank=True)
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2,
                                         null=False, blank=False,
                                         editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=155)
    friendly_name = models.CharField(max_length=155, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    User = get_user_model()
    category = models.ForeignKey(
        'Category', null=True, blank=True, on_delete=models.SET_NULL
    )
    sku = models.CharField(max_length=55, unique=True)
    name = models.CharField(max_length=155)
    subtitle = models.CharField(max_length=205)
    description = models.TextField()
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    size = models.CharField(max_length=6, null=True, blank=True)
    intensity = models.IntegerField(null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.IntegerField(null=True, blank=True)
    date_added = models.DateField(null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    users_wishlist = models.ManyToManyField(
        User, related_name='user_wishlist', blank=True
    )

    def __str__(self):
        return self.name


class Review(models.Model):
    """
    Models the fields for adding product reviews.
    """
    User = get_user_model()
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='reviews'
    )
    username = models.ForeignKey(User, on_delete=models.CASCADE,
                                 related_name='user_reviews')
    message = models.TextField(help_text='Add your review here')
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return f'Review {self.message} by {self.username}'

products/forms.py
from django import forms
from .models import Product, Category, Review
from .widgets import CustomClearableFileInput


class ProductForm(forms.ModelForm):
    """
    Uses Django form to create
    a form for product details
    """
    class Meta:
        model = Product
        fields = ['category', 'sku', 'name', 'subtitle', 'description', 'has_sizes', 'size', 'intensity', 'price', 'rating', 'date_added', 'image_url', 'image']

    image = forms.ImageField(label='Image', required=False,
                             widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'rounded-0'


class ReviewForm(forms.ModelForm):
    """
    Uses Django form to enable users
    to add product reviews within
    Post Detail view.
    """
    class Meta:
        model = Review
        fields = ('message',)

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views import generic, View
from django.views.generic import DeleteView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.db.models import Q
from django.db.models.functions import Lower
from .models import Product, Category, Review
from .forms import ProductForm, ReviewForm


def all_products(request):
    """ A view to show all products, including sorting and search queries """

    products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None
    # Handle the page request to sort products
    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        # Handle the page request to return a specific category
        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        # Handle the page request to query the database
        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "Please enter a search criteria")
                return redirect(reverse('products'))

            queries = Q(name__icontains=query) | \
                Q(description__icontains=query)
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    # Context to return to the page
    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }
    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """
    A view to show a single product in detail
    and enable signed in users to add reviews
    """

    # Return the requested product or 404
    product = get_object_or_404(Product, pk=product_id)
    reviews = product.reviews.order_by('-created_on')

    if request.user.is_authenticated:
        review_form = ReviewForm(data=request.POST)

        if review_form.is_valid():
            review_form.instance.username = request.user
            review = review_form.save(commit=False)
            review.product = product
            review.save()
            messages.success(request, 'Thank you for taking \
                the time to provide a review')

    # Context to return to the page
    context = {
        'product': product,
        'reviews': reviews,
        'reviewed': False,
        'review_form': ReviewForm(),
    }
    return render(request, 'products/product_detail.html', context)


@login_required
def add_product(request):
    """ Add a product from the front end """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only the owners can do that')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Product added successfully')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to add product. \
                            Please ensure the form is completed correctly')
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
    }
    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """ Edit a product from the front end """
    # if not superuser redirect home
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only the owners can do that')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated the product')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to update product. \
                            Please ensure the form is completed correctly')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }
    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """ Delete a product from the front end """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only the owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)

    if request.method == 'POST':
        product.delete()
        messages.success(request, f'{product.name} successfully deleted.')
        return redirect(reverse('products'))

    return render(request, 'products/confirm_delete.html')

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}{% trans 'Add Product' %}{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/products.css' %}">
{% endblock %}

{% block content %}
<!-- Page header -->
<div class="container-fluid">
    <div class="row">
        <div class="col text-center mt-3 mb-3">
            <h1 class="page-title">Product Management</h1>
            <hr class="w-50 mb-1">
        </div>
    </div>
    <!-- Container for Add Product form -->
    <div class="row">
        <div class="col-12 col-md-6 mb-4">
            <h2 class="page-subtitle mb-3">Add a Product</h2>
            <form action="{% url 'add_product' %}" class="form mb-2" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                {% if field.name != 'image' %}
                {{ field | as_crispy_field }}
                {% else %}
                {{ field }}
                {% endif %}
                {% endfor %}
                <div class="text-left">
                    <!-- Cancel button -->
                    <a href="{% url 'products' %}" class="btn rounded-0 back-btn cancel-anchor-btn">Cancel</a>
                    <!-- Submit button -->
                    <button class="btn rounded-0 standard-btn" type="submit">Add Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script>
    $('#new-image').change(function () {
        var file = $('#new-image')[0].files[0];
        $('#filename').text(`Image will be set to: ${file.name}`);
    });
</script>
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}{% trans 'Edit Product' %}{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/products.css' %}">
{% endblock %}

{% block content %}
<!-- Page header -->
<div class="container-fluid">
    <div class="row">
        <div class="col text-center mt-3 mb-3">
            <h1 class="page-title">Product Management</h1>
            <hr class="w-50 mb-1">
        </div>
    </div>
    <!-- Container for Edit Product form -->
    <div class="row">
        <div class="col-12 col-md-6 mb-4">
            <h2 class="page-subtitle mb-3">Edit a Product</h2>
            <form action="{% url 'edit_product' product.id %}" class="form mb-2" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.name != 'image' %}
                        {{ field | as_crispy_field }}
                    {% else %}
                        {{ field }}
                    {% endif %}
                {% endfor %}
                <div class="text-left">
                    <!-- Cancel button -->
                    <a href="{% url 'products' %}" class="btn rounded-0 back-btn cancel-anchor-btn">Cancel</a>
                    <!-- Submit button -->
                    <button class="btn rounded-0 standard-btn" type="submit">Submit Updates</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script>
    $('#new-image').change(function () {
        var file = $('#new-image')[0].files[0];
        $('#filename').text(`Image will be set to: ${file.name}`);
    });
</script>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}{% trans 'Product Detail' %}{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/products.css' %}">
{% endblock %}

<!-- Crispy Forms to render form for adding a product review-->
{% load crispy_forms_tags %}

{% block content %}
<!-- Page header -->
<div class="container-fluid">
    <!-- Container for product details -->
    <div class="row">
        <div class="col-md-6 product-details-container mt-3">
            <!-- Title, Subtitle, Description -->
            <div class="card-body pb-0">
                <h2 class="card-title title-font product-detail-title mb-4">{{ product.name }}</h2>
                <h3 class="card-subtitle mb-4">{{ product.subtitle }}</h3>
                <p class="card-description mb-4">{{ product.description }}</p>
            </div>
            <!-- Price, Rating, Quantity, Size, Buttons -->
            <div class="card-footer bg-white pt-0 border-0 text-left mb-3">
                <!-- Intensity -->
                <div class="row">
                    <div class="col">
                        {% with product.intensity as s %}
                        {% if s %}
                        {% if product.category.name == "ground_coffee" %}
                        <p class="card-description mb-2"><strong>Intensity:</strong> {{ product.intensity }} / 10</p>
                        {% elif product.category.name == "coffee_beans" %}
                        <p class="card-description mb-2"><strong>Intensity:</strong> {{ product.intensity }} / 10</p>
                        {% endif %}
                        {% endif %}
                        {% endwith %}
                    </div>
                </div>
                <!-- Rating -->
                <div class="row">
                    <div class="col">
                        {% if product.rating %}
                        <p class="rating-icon card-description mb-2"><strong>Rating:</strong> {{ product.rating }} /
                            5 <i class="fa-sharp fa-solid fa-mug-saucer"></i></p>
                        {% else %}
                        <p class="text-muted card-description mb-2">No Rating</p>
                        {% endif %}
                    </div>
                </div>
                <!-- Price -->
                <div class="row">
                    <div class="col">
                        <p class="card-description mb-2"><strong>Price:</strong> £{{ product.price }}</p>
                    </div>
                </div>
                <!-- Size, Quantity -->
                <div class="row">
                    <div class="col">
                        <!-- Form to input size and qty info -->
                        <form class="form size-qty-input-form" action="{% url 'add_to_bag' product.id %}" method="POST">
                            {% csrf_token %}
                            <!-- Size -->
                            <div class="form-row">
                                {% with product.has_sizes as s %}
                                {% if s %}
                                {% if product.category.name == "ground_coffee" %}
                                <p class="card-description mb-2"><strong>Size:</strong></p>
                                <div class="form-group">
                                    <select class="form-control" name="product_size" id="id_product_size">
                                        <option value="200g">200g</option>
                                        <option value="500g">500g</option>
                                        <option value="1kg">1kg</option>
                                    </select>
                                </div>
                                {% elif product.category.name == "coffee_beans" %}
                                <p class="card-description mb-2"><strong>Size:</strong></p>
                                <div class="form-group">
                                    <select class="form-control" name="product_size" id="id_product_size">
                                        <option value="200g">200g</option>
                                        <option value="500g">500g</option>
                                        <option value="1kg">1kg</option>
                                    </select>
                                </div>
                                {% elif product.category.name == "coffee_clothing" %}
                                <p class="card-description mb-2"><strong>Size:</strong></p>
                                <div class="form-group">
                                    <select class="form-control" name="product_size" id="id_product_size">
                                        <option value="Small">Small</option>
                                        <option value="Medium">Medium</option>
                                        <option value="Large">Large</option>
                                    </select>
                                </div>
                                {% endif %}
                                {% endif %}
                            </div>
                            <!-- Quantity -->
                            <div class="form-row">
                                <p class="card-description mb-3"><strong>Quantity:</strong></p>
                                <div class="form-group">
                                    <div class="input-group input-group-{{ product.id }}">
                                        <!-- Decrease quantity button -->
                                        <div class="input-group-prepend">
                                            <button id="al" aria-label="Reduce quantity"
                                                class="decrement-qty btn decrement-qty_{{ product.id }}"
                                                data-item_id="{{ product.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-minus"></i>
                                                </span>
                                            </button>
                                        </div>
                                        <!-- Quantity -->
                                        <input class="form-control qty_input id_qty_{{ product.id }}" type="number"
                                            name="quantity" value="1" min="1" max="99" data-item_id="{{ product.id }}"
                                            id="id_qty_{{ product.id }}" aria-label="Quantity">
                                        <!-- Increase quantity button -->
                                        <div class="input-group-append">
                                            <button id="al" aria-label="Increase quantity"
                                                class="increment-qty btn increment-qty_{{ product.id }}"
                                                data-item_id="{{ product.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-plus"></i>
                                                </span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- Form buttons -->
                            <div class="form-row mt-3 mb-3">
                                <div class="col">
                                    <!-- Back to products page -->
                                    <a href="{% url 'products' %}" class="btn back-btn">Keep<br>Shopping</a>
                                    <!-- Add product to bag -->
                                    <input type="submit" class="btn standard-btn" value="Add to Bag">
                                </div>
                                <input type="hidden" name="redirect_url" value="{{ request.path }}">
                            </div>
                            {% endwith %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- Product image (if available) -->
        <div class="col-md-6 product-img-container mt-3 mb-3 text-center">
            {% if product.image %}
            <a href="">
                <img class="card-img-top img-fluid xl-screen-img" src="{{ product.image.url }}"
                    alt="{{ product.name }}">
            </a>
            {% else %}
            <a href="">
                <img class="card-img-top img-fluid xl-screen-img" src="{{ MEDIA_URL }}noimage.png"
                    alt="{{ product.name }}">
            </a>
            {% endif %}
        </div>
    </div>
    <!-- Container for Admins only to Edit/Delete Products -->
    {% if request.user.is_superuser %}
    <div class="row admin-links-container">
        <div class="col-12 mt-2 mb-4">
            <a class="admin-links" style="color:#155724" href="{% url 'edit_product' product.id %}">Edit</a>
            <a class="admin-links" style="color:#721c24;" href="{% url 'delete_product' product.id %}">Delete</a>
        </div>
    </div>
    {% endif %}
    <!--- Container for product reviews -->
    <div class="container-fluid mt-2 mb-4">
        <div class="row">
            <!--- Container for product reviews -->
            <div class="col-md-6 card mb-4 mt-3 border-0">
                <div class="card-body">
                    <h3 class="card-subtitle mb-2 cust-review-h3" style="color: #351c75">Customer Reviews
                    </h3>
                    {% for review in reviews %}
                    <div class="card-body mt-3 mb-3">
                        <p class="card-text">{{ review.username }} said:
                        </p>
                        <p class="card-text"><i>
                                {{ review.message | linebreaks }}</i></p>
                        <span class="text-muted">
                            {{ review.created_on }}
                        </span>
                    </div>
                    {% endfor %}
                </div>
                <!-- Container for adding product reviews -->
                <div class="card-body">
                    <!--- Link to inform how registration is required -->
                    {% if not user.is_authenticated %}
                    <div class="card-body">
                        <h3 class="card-subtitle mb-2" style="color: #351c75">Would you like to review this product?
                        </h3>
                        <div class="card-body mb-3">
                            <p class="card-text register-text">Please either <a style="color:#351c75"
                                    href="{% url 'account_login' %}"><strong>sign in</strong></a> to your account or
                                register first.
                            </p>
                            <a href="{% url 'account_signup' %}" class="btn standard-btn register-btn">Register
                            </a>
                        </div>
                    </div>
                    <!--- Signed in user can leave a product review -->
                    {% else %} {% if user.is_authenticated %}
                    <div class="card-body">
                        <h3 class="card-subtitle cust-review-h3" style="color: #351c75">Leave your review
                        </h3>
                        <div class="card-body">
                            <p class="card-text">
                                Reviewing as:
                                <span>{{ user.username }}
                                </span>
                            </p>
                            <!---User feature to add product review  -->
                            <form method="post" style="margin-top: 1.3em;">
                                {{ review_form | crispy }} {% csrf_token %}
                                <!---Button to submit product review -->
                                <button type="submit" class="standard-btn">Submit
                                </button>
                            </form>
                        </div>
                    </div>
                    {% endif %} {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}